title: Davor Vezmar # your name (or website title) here
logo: "/images/DaxSlikaZaPortf.jfif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me 
  <br><br>
  Second description 
  <br><br>
  Third description 
  <br><br>
  <a href="https://www.linkedin.com/in/davor-vezmar-18268822a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
